const SPOT = "https://api.mexc.com"; const FUTURES = "https://contract.mexc.com";
async function json(url, retries = 3) { for (let i=0;i<retries;i++) { const r=await fetch(url,{headers:{"User-Agent":"SignalGrid/1.0"}}); if(r.ok) return r.json(); if(r.status!==429&&r.status<500) throw new Error(`${r.status} ${url}`); await new Promise(x=>setTimeout(x,500*2**i)); } throw new Error(`MEXC unavailable: ${url}`); }
export async function discoverMarkets() {
  const [spotInfo, spotTickers, contracts, contractTickers] = await Promise.all([json(`${SPOT}/api/v3/exchangeInfo`), json(`${SPOT}/api/v3/ticker/24hr`), json(`${FUTURES}/api/v1/contract/detail`).catch(()=>({data:[]})), json(`${FUTURES}/api/v1/contract/ticker`).catch(()=>({data:[]}))]);
  const ticker = new Map(spotTickers.map(t=>[t.symbol,t])); const spot = spotInfo.symbols.filter(s=>(s.status==="1"||s.status==="ENABLED")&&String(s.quoteAsset).toUpperCase()==="USDT").map(s=>({symbol:s.symbol,base:s.baseAsset,quote:"USDT",market:"SPOT",ticker:ticker.get(s.symbol)}));
  const perpTicker = new Map((Array.isArray(contractTickers.data)?contractTickers.data:[contractTickers.data]).filter(Boolean).map(t=>[t.symbol,{lastPrice:t.lastPrice,priceChangePercent:Number(t.riseFallRate||0)*100,quoteVolume:t.amount24}]));
  const perp=(contracts.data||[]).filter(c=>(c.state===0||c.state===1)&&String(c.quoteCoin).toUpperCase()==="USDT").map(c=>({symbol:String(c.symbol).replace("_",""),apiSymbol:c.symbol,base:c.baseCoin,quote:"USDT",market:"PERP",ticker:perpTicker.get(c.symbol)})); return [...spot,...perp];
}
function mapSpot(row){return{openTime:Number(row[0]),open:Number(row[1]),high:Number(row[2]),low:Number(row[3]),close:Number(row[4]),volume:Number(row[5]),closeTime:Number(row[6])}}
export async function spotCandles(symbol, interval, limit=260){return (await json(`${SPOT}/api/v3/klines?symbol=${symbol}&interval=${interval}&limit=${limit}`)).map(mapSpot)}
export async function perpCandles(symbol, interval, limit=260){const end=Math.floor(Date.now()/1000);const start=end-limit*({Min60:3600,Hour4:14400,Day1:86400,Week1:604800}[interval]||3600);const d=(await json(`${FUTURES}/api/v1/contract/kline/${symbol}?interval=${interval}&start=${start}&end=${end}`)).data;return (d?.time||[]).map((t,i)=>({openTime:t*1000,open:+d.open[i],high:+d.high[i],low:+d.low[i],close:+d.close[i],volume:+d.vol[i],closeTime:(t+3600)*1000-1}))}
